# Docker compose to build and run the eureka service
version: '3'
services:
  zuul-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8079:8079"

networks:
  default:
    external:
      name: springboot