zuul:
  #Service will be mapped under the /api URI
  prefix: /api/attosoft-corp
  routes:
    hello-service:
      path: /server/**
      serviceId: HELLO-SERVICE
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://atto-eureka-server.common.svc:8080/eureka/
  instance:
    hostname: atto-eureka-server.common.svc

spring:
  application:
    name: atto-zuul-server.common.svc

server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000