zuul:
  #Service will be mapped under the /api URI
  prefix: /api/attosoft-corp
  routes:
    hello-service:
      path: /server/**
      serviceId: HELLO-SERVICE
      # url: http://hello-service:5000
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server

server:
  port: 8079

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000