spring:
  application:
    name: atto-zuul-server.common.svc

server:
  port: 8080

zuul:
  #Service will be mapped under the /api URI
  prefix: /api/attosoft-corp
  routes:
    hello-service:
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://atto-eureka-server.common.svc:8080/eureka/
  instance:
    hostname: atto-eureka-server.common.svc